「PyTorchとは？」
===============================================================
【原題】What is PyTorch?

【原著】[Soumith Chintala](http://soumith.ch/)

【元URL】https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

【翻訳】電通国際情報サービスISID AIトランスフォーメーションセンター　徳原 光

【日付】2020年10月13日

【チュトーリアル概要】

本チュートリアルでは、PyTorchでの演算処理に用いるTorch Tensorについて、その操作方法を解説します。

---



PyTorchとは？
================

PyTorchはPythonをベースとした科学計算ライブラリです。

PyTorchは以下に示す2つの機能を使用したいユーザーを対象としています。

- Numpyベースの演算の代わりに、GPUを用いた高速な演算の実施
- 高い柔軟性と実行速度を有したディープラーニングのプラットフォーム




Tensors（テンソル）
-------------

TensorはNumPy ndarraysのような多次元配列です。

PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能です。

In [ ]:
%matplotlib inline

In [ ]:
# from __future__ import print_function
# import torch

In [ ]:
from __future__ import print_function
import torch

【注意】

初期化されていない行列が宣言・作成されても、実際に使用されるまで明確な値は保有していません。

宣言時にメモリ上の割り当てられた適当な値が初期値として入っています。




初期化されていない、3×5行列を生成してみましょう：



In [ ]:
# x = torch.empty(5, 3)
# print(x)

In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[6.6463e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


次に、乱数によって初期化された3x5行列を生成してみましょう:



In [ ]:
# x = torch.rand(5, 3)
# print(x)

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5038, 0.9606, 0.5691],
        [0.9894, 0.0454, 0.7251],
        [0.1370, 0.0041, 0.5591],
        [0.7339, 0.0983, 0.4560],
        [0.3185, 0.4829, 0.4849]])


long型の数値0で初期化された行列を生成する場合は次の通りです。



In [ ]:
# x = torch.zeros(5, 3, dtype=torch.long)
# x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接、数値を指定して行列を生成することもできます。



In [ ]:
# x = torch.tensor([5.5, 3], dtype=torch.long)
# x

tensor([5.5000, 3.0000])

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


その他に、すでにあるtensorをもとに、新しくtensorを生成することもできます。

本メソッドで生成したテンソルは、テンソルの特性（例えばデータ型：dtypeなど）を、もとのtensorから引き継ぎます（ユーザーが値や特性を直接上書きしない限り）。

In [ ]:
# import torch
# import numpy as np

# # テンソルの新規作成
# x = torch.empty(2, 3) # 2行×3列のテンソル（未初期化状態）を生成
# x = torch.rand(2, 3)  # 2行×3列のテンソル（ランダムに初期化）を生成
# x = torch.zeros(2, 3, dtype=torch.float) # 2行×3列のテンソル（0で初期化、torch.float型）を生成
# x = torch.ones(2, 3, dtype=torch.float)  # 2行×3列のテンソル（1で初期化、torch.float型）を生成
# x = torch.tensor([[0.0, 0.1, 0.2],
#                   [1.0, 1.1, 1.2]])      # 1行×2列のテンソルをPythonリスト値から作成

# # 既存のテンソルを使った新規作成
# # 「new_*()」パターン
# y = x.new_ones(2, 3)   # 2行×3列のテンソル（1で初期化、既存のテンソルと「同じデータ型」）を生成
# # 「*_like()」パターン # 既存のテンソルと「同じサイズ」のテンソル（1で初期化、torch.int型）を生成
# y = torch.ones_like(x, dtype=torch.int)
# y

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
# x = x.new_ones(5, 3, dtype=torch.double)
# print(x)

# x = torch.randn_like(x, dtype=torch.float)
# print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1072, -0.0824, -0.9604],
        [-0.8681, -1.0503,  0.8826],
        [ 0.3431,  1.2594, -0.6635],
        [ 0.2788, -0.0113, -0.8235],
        [ 0.0937,  0.7254,  0.6754]])


In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2299,  0.8970,  0.1323],
        [-1.1328,  0.6298,  1.4558],
        [ 0.8885, -1.6032,  0.7505],
        [ 0.3868, -0.8734,  1.4104],
        [-0.4534,  0.1195, -0.9755]])


テンソルサイズ（size）≒テンソルの形、を求めてみます。



In [ ]:
print(x.size())

torch.Size([5, 3])


【メモ】

``torch.Size``はタプルとなっているため、Pythonの通常のタプルと同様の操作が可能です。

**テンソルの操作（変形・変換等）**


PyTorchにはテンソルに対する操作（変形・変換等）が多く用意されています。

ここで、tensorを操作（変形・変換等）する追加の例を紹介します。



補足: 用例1

In [ ]:
# y = torch.rand(5, 3)
# print(x @ y.T)

tensor([[-0.4657, -0.1267, -0.0602,  0.1401, -0.5390],
        [ 0.2424,  0.1149,  1.0844,  0.4411,  0.1844],
        [ 0.4360, -0.5888,  0.3106, -0.0594,  0.5821],
        [ 0.7289, -0.0840,  1.0525,  0.2247,  0.8019],
        [-0.8291, -0.5849, -1.0960, -0.2560, -0.8256]])


In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.5497,  1.7893,  0.6868],
        [-0.3208,  1.3220,  2.1799],
        [ 1.5776, -1.2873,  1.3336],
        [ 0.6011,  0.0357,  2.2423],
        [-0.2669,  0.1705, -0.8588]])


補足: 用例2



In [ ]:
# print(torch.add(x, y))

tensor([[-0.5497,  1.7893,  0.6868],
        [-0.3208,  1.3220,  2.1799],
        [ 1.5776, -1.2873,  1.3336],
        [ 0.6011,  0.0357,  2.2423],
        [-0.2669,  0.1705, -0.8588]])


In [ ]:
print(torch.add(x, y))

tensor([[-0.5497,  1.7893,  0.6868],
        [-0.3208,  1.3220,  2.1799],
        [ 1.5776, -1.2873,  1.3336],
        [ 0.6011,  0.0357,  2.2423],
        [-0.2669,  0.1705, -0.8588]])


補足: 出力先を引数で指定 



In [ ]:
# result = torch.empty(5, 3)
# torch.add(x, y, out=result)
# print(result)

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.5497,  1.7893,  0.6868],
        [-0.3208,  1.3220,  2.1799],
        [ 1.5776, -1.2873,  1.3336],
        [ 0.6011,  0.0357,  2.2423],
        [-0.2669,  0.1705, -0.8588]])


補足：テンソルそのものの変更（in-place：インプレース処理）



In [ ]:
# y.add_(x)

In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.5497,  1.7893,  0.6868],
        [-0.3208,  1.3220,  2.1799],
        [ 1.5776, -1.2873,  1.3336],
        [ 0.6011,  0.0357,  2.2423],
        [-0.2669,  0.1705, -0.8588]])


【メモ】

メソッド名の後に``_``をつけることで、変数の内容を出力結果で置き換えることができます。

例えば、``y.add_(x)``の場合xとyの値を加算した結果はyに上書きして、格納されます。

NumPyと同様、インデクシングやスライシングを行うことも可能です。

In [ ]:
# x.shape

torch.Size([5, 3])

In [ ]:
print(x[:, 1])

tensor([ 0.8970,  0.6298, -1.6032, -0.8734,  0.1195])


リサイズ: tensorの形を変えたい場合は ``torch.view``を使用してください:



In [ ]:
# x = torch.randn(4, 4)
# y = x.view(16)
# z = x.view(-1, 8)
# print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  -1を指定すると他に設定した次元の値から自動で計算
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


``.item()``を使用すると、要素を1つしか持たないtensorから、中身の数値だけを取り出すことができます。


In [ ]:
# x = torch.randn(1)
# print(x)
# x.item()

tensor([-0.1351])


-0.13507966697216034

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1100])
-1.1099542379379272


**参考:**

PyTorchでは、転置、インデックシング、スライシング、演算処理、線形代数、乱数生成などの100を超える機能が提供されています。

詳しくは[こちらのページ](https://pytorch.org/docs/stable/torch.html)をご覧ください。

NumPyとの接続
------------

PyTorchではTorch TensorからNumPy Arrayへの変換やその逆を簡単に行うことできます。

（Torch TensorがCPU上にある場合）Torch TensorとNumPy Arrayはメモリ上の同じ領域に配置され、変換することができます。



Torch Tensorから NumPy Arrayへの変換
--------




In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# b = a.numpy()
# print(b)

[1. 1. 1. 1. 1.]


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


メモリを共有しているため、Torch Tensorの値がNumPy Arrayにも反映されることが分かります。



In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy ArrayからTorch Tensorへの変換
---------

NumPy ArrayからTorch Tensorへの変換も、容易に可能です。



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensorを除き、CPU上のすべてのTensorはNumPyへの変換、およびその逆（NumpyからTensor）に対応しています。


CUDA Tensors（CUDA テンソル）
------------

tensorは ``.to`` メソッドを使用することであらゆるデバイス上のメモリへと移動させることができます。

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


# 日本語訳注：
# tensor([1.8299], device='cuda:0')
# tensor([1.8299], dtype=torch.float64)
# のような出力（値は変わります）がセルのあとに表示されれば、GPUでのCUDAでのテンソル計算が成功しています。
# もし、何も表示されなければ、Google ColaroboratoryがGPU使用モードになっていないので、
# 下のセルの説明を読んで、GPUを使用可能な状態にしてみてください。

tensor([-0.1100], device='cuda:0')
tensor([-0.1100], dtype=torch.float64)


（日本語訳注）

Google ColaboratoryでCUDA、すなわちGPUを使用可能にするには、上部メニューの「ランタイム」を選択し、「ランタイムのタイプを変更」で、「ハードウェア アクセラレータ」にGPUを選択します。


上記で、現在のランタイムの環境を確認し、GPUでなければ、GPUに設定して、上記セルを実行してみてください。